# Remove unused files, or files that should not be used

rm -rf `find $VENDOR_SPARSE -name .gitignore`
rm -rf $VENDOR_SPARSE/app
rm -rf $VENDOR_SPARSE/bin/apedata_mount.sh
rm -rf $VENDOR_SPARSE/bin/exp-log.sh
rm -rf $VENDOR_SPARSE/bin/install-recovery.sh
# Remove iptables binaries (these litter our iptables tables)
rm -rf $VENDOR_SPARSE/bin/ip6tables
rm -rf $VENDOR_SPARSE/bin/iptables
rm -rf $VENDOR_SPARSE/bin/logd-catch.sh
rm -rf $VENDOR_SPARSE/bin/preinstall.sh
rm -rf $VENDOR_SPARSE/bin/tinno_audio_dump.sh
rm -rf $VENDOR_SPARSE/build.prop.bakforspec
rm -rf $VENDOR_SPARSE/etc/cdrom_install.iso
rm -rf $VENDOR_SPARSE/etc/install_apk.sh
rm -rf $VENDOR_SPARSE/etc/mmi/fonts.ttf
rm -rf $VENDOR_SPARSE/etc/recovery-resource.dat
rm -rf $VENDOR_SPARSE/etc/security/otacerts.zip
rm -rf $VENDOR_SPARSE/fonts
rm -rf $VENDOR_SPARSE/framework
rm -rf $VENDOR_SPARSE/lib/libchromium_client.so
rm -rf $VENDOR_SPARSE/lib/libjni_pacprocessor.so
rm -rf $VENDOR_SPARSE/lib/libpac.so
rm -rf $VENDOR_SPARSE/lib/libswenetxt_plugin.so
rm -rf $VENDOR_SPARSE/lib/libsweskia.so
rm -rf $VENDOR_SPARSE/lib/libswev8.so
rm -rf $VENDOR_SPARSE/lib/libswewebviewchromium.so
rm -rf $VENDOR_SPARSE/lib/libwebviewchromium_loader.so
rm -rf $VENDOR_SPARSE/lib/libwebviewchromium_plat_support.so
rm -rf $VENDOR_SPARSE/lib/libwebviewchromium.so
rm -rf $VENDOR_SPARSE/lib/libWnnEngDic.so
rm -rf $VENDOR_SPARSE/lib/libWnnJpnDic.so
rm -rf $VENDOR_SPARSE/lib/modules
rm -rf $VENDOR_SPARSE/lost+found
rm -rf $VENDOR_SPARSE/media
rm -rf $VENDOR_SPARSE/overlay
rm -rf $VENDOR_SPARSE/plugin
rm -rf $VENDOR_SPARSE/priv-app
rm -rf $VENDOR_SPARSE/recovery-from-boot.p
rm -rf $VENDOR_SPARSE/tts
rm -rf $VENDOR_SPARSE/usr/hyphen-data
rm -rf $VENDOR_SPARSE/usr/keylayout
rm -rf $VENDOR_SPARSE/usr/qfipsverify/bootimg.hmac
rm -rf $VENDOR_SPARSE/vendor/app
rm -rf $VENDOR_SPARSE/vendor/bin/slim_ap_daemon
rm -rf $VENDOR_SPARSE/vendor/Cambodia
rm -rf $VENDOR_SPARSE/vendor/CherryCommon
rm -rf $VENDOR_SPARSE/vendor/ChinaMobile
rm -rf $VENDOR_SPARSE/vendor/ChinaTelecom
rm -rf $VENDOR_SPARSE/vendor/ChinaUnicom
rm -rf $VENDOR_SPARSE/vendor/CmccPower
rm -rf $VENDOR_SPARSE/vendor/CTA
rm -rf $VENDOR_SPARSE/vendor/data/misc/ProjectConfig.mk
rm -rf $VENDOR_SPARSE/vendor/Default/system/media
rm -rf $VENDOR_SPARSE/vendor/DTGermany
rm -rf $VENDOR_SPARSE/vendor/EEEU
rm -rf $VENDOR_SPARSE/vendor/EEUK
rm -rf $VENDOR_SPARSE/vendor/etc/scve
rm -rf $VENDOR_SPARSE/vendor/etc/voicecommand
rm -rf $VENDOR_SPARSE/vendor/EUCommon
rm -rf $VENDOR_SPARSE/vendor/framework
rm -rf $VENDOR_SPARSE/vendor/H3GItalia
rm -rf $VENDOR_SPARSE/vendor/H3GUK
rm -rf $VENDOR_SPARSE/vendor/IndonesiaOpenmarket
rm -rf $VENDOR_SPARSE/vendor/LanixClaroColombia
rm -rf $VENDOR_SPARSE/vendor/LanixTelcelMexico
rm -rf $VENDOR_SPARSE/vendor/Laos
rm -rf $VENDOR_SPARSE/vendor/LatamAMX
rm -rf $VENDOR_SPARSE/vendor/LatamBrazil
rm -rf $VENDOR_SPARSE/vendor/LatamClaroChile
rm -rf $VENDOR_SPARSE/vendor/LatamClaroColombia
rm -rf $VENDOR_SPARSE/vendor/LatamClaroPeru
rm -rf $VENDOR_SPARSE/vendor/LatamTelcelMexico
rm -rf $VENDOR_SPARSE/vendor/LatamTelefonica*
rm -rf $VENDOR_SPARSE/vendor/lib/modules
rm -rf $VENDOR_SPARSE/vendor/MalaysiaOpenMarket
rm -rf $VENDOR_SPARSE/vendor/media
rm -rf $VENDOR_SPARSE/vendor/NorthAmerica
rm -rf $VENDOR_SPARSE/vendor/OrangeFrance
rm -rf $VENDOR_SPARSE/vendor/PhilippinesOpenMarket
rm -rf $VENDOR_SPARSE/vendor/plugin
rm -rf $VENDOR_SPARSE/vendor/priv-app
rm -rf $VENDOR_SPARSE/vendor/res
rm -rf $VENDOR_SPARSE/vendor/RJIL
rm -rf $VENDOR_SPARSE/vendor/RussiaOpen
rm -rf $VENDOR_SPARSE/vendor/speccfg
rm -rf $VENDOR_SPARSE/vendor/TelefonicaGermany
rm -rf $VENDOR_SPARSE/vendor/TelefonicaSpain
rm -rf $VENDOR_SPARSE/vendor/ThailandOpenMarket
rm -rf $VENDOR_SPARSE/vendor/TurkeyOpen
rm -rf $VENDOR_SPARSE/vendor/VadafoneUK
rm -rf $VENDOR_SPARSE/vendor/Vodafone*
