%define multiple_rpms 1
%define rpm_device akatsuki

%define variant -vendor

%define dsd_path ./

Requires(post): coreutils
Requires(post): libcap

%include droid-system-device/droid-system.inc

# rest of this file is autogenerated. do not edit
%post
[ -e /vendor/bin ] && chown 0:2000 /vendor/bin
[ -e /vendor/bin/awk ] && chown 0:2000 /vendor/bin/awk
[ -e /vendor/bin/grep ] && chown 0:2000 /vendor/bin/grep
[ -e /vendor/bin/hw ] && chown 0:2000 /vendor/bin/hw
[ -e /vendor/bin/hw/android.hardware.audio@2.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.audio@2.0-service
[ -e /vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony ] && chown 0:2000 /vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony
[ -e /vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti ] && chown 0:2000 /vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti
[ -e /vendor/bin/hw/android.hardware.boot@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.boot@1.0-service
[ -e /vendor/bin/hw/android.hardware.camera.provider@2.4-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.camera.provider@2.4-service
[ -e /vendor/bin/hw/android.hardware.cas@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.cas@1.0-service
[ -e /vendor/bin/hw/android.hardware.configstore@1.1-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.configstore@1.1-service
[ -e /vendor/bin/hw/android.hardware.drm@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.drm@1.0-service
[ -e /vendor/bin/hw/android.hardware.drm@1.1-service.clearkey ] && chown 0:2000 /vendor/bin/hw/android.hardware.drm@1.1-service.clearkey
[ -e /vendor/bin/hw/android.hardware.gnss@1.1-service-qti ] && chown 0:2000 /vendor/bin/hw/android.hardware.gnss@1.1-service-qti
[ -e /vendor/bin/hw/android.hardware.graphics.allocator@2.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.graphics.allocator@2.0-service
[ -e /vendor/bin/hw/android.hardware.graphics.composer@2.1-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.graphics.composer@2.1-service
[ -e /vendor/bin/hw/android.hardware.health@2.0-service.sony ] && chown 0:2000 /vendor/bin/hw/android.hardware.health@2.0-service.sony
[ -e /vendor/bin/hw/android.hardware.light@2.0-service.sony ] && chown 0:2000 /vendor/bin/hw/android.hardware.light@2.0-service.sony
[ -e /vendor/bin/hw/android.hardware.media.omx@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.media.omx@1.0-service
[ -e /vendor/bin/hw/android.hardware.memtrack@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.memtrack@1.0-service
[ -e /vendor/bin/hw/android.hardware.nfc@1.1-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.nfc@1.1-service
[ -e /vendor/bin/hw/android.hardware.power@1.3-service.sony ] && chown 0:2000 /vendor/bin/hw/android.hardware.power@1.3-service.sony
[ -e /vendor/bin/hw/android.hardware.sensors@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.sensors@1.0-service
[ -e /vendor/bin/hw/android.hardware.thermal@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.thermal@1.0-service
[ -e /vendor/bin/hw/android.hardware.usb@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.usb@1.0-service
[ -e /vendor/bin/hw/android.hardware.vibrator@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.vibrator@1.0-service
[ -e /vendor/bin/hw/android.hardware.wifi@1.0-service ] && chown 0:2000 /vendor/bin/hw/android.hardware.wifi@1.0-service
[ -e /vendor/bin/hw/hostapd ] && chown 0:2000 /vendor/bin/hw/hostapd
[ -e /vendor/bin/hw/rild ] && chown 0:2000 /vendor/bin/hw/rild
[ -e /vendor/bin/hw/wpa_supplicant ] && chown 0:2000 /vendor/bin/hw/wpa_supplicant
[ -e /vendor/bin/init.qcom.adspstart.sh ] && chown 0:2000 /vendor/bin/init.qcom.adspstart.sh
[ -e /vendor/bin/init.qcom.cdspstart.sh ] && chown 0:2000 /vendor/bin/init.qcom.cdspstart.sh
[ -e /vendor/bin/init.qcom.ipastart.sh ] && chown 0:2000 /vendor/bin/init.qcom.ipastart.sh
[ -e /vendor/bin/init.qcom.slpistart.sh ] && chown 0:2000 /vendor/bin/init.qcom.slpistart.sh
[ -e /vendor/bin/ipacm ] && chown 0:2000 /vendor/bin/ipacm
[ -e /vendor/bin/logwrapper ] && chown 0:2000 /vendor/bin/logwrapper
[ -e /vendor/bin/macaddrsetup ] && chown 0:2000 /vendor/bin/macaddrsetup
[ -e /vendor/bin/sh ] && chown 0:2000 /vendor/bin/sh
[ -e /vendor/bin/timekeep ] && chown 0:2000 /vendor/bin/timekeep
[ -e /vendor/bin/toolbox ] && chown 0:2000 /vendor/bin/toolbox
[ -e /vendor/bin/toybox_vendor ] && chown 0:2000 /vendor/bin/toybox_vendor
[ -e /vendor/bin/vndservice ] && chown 0:2000 /vendor/bin/vndservice
[ -e /vendor/bin/vndservicemanager ] && chown 0:2000 /vendor/bin/vndservicemanager
[ -e /vendor/bt_firmware ] && chown 0:2000 /vendor/bt_firmware
[ -e /vendor/dsp ] && chown 0:2000 /vendor/dsp
[ -e /vendor/etc ] && chown 0:2000 /vendor/etc
[ -e /vendor/etc/acdbdata ] && chown 0:2000 /vendor/etc/acdbdata
[ -e /vendor/etc/data ] && chown 0:2000 /vendor/etc/data
[ -e /vendor/etc/init ] && chown 0:2000 /vendor/etc/init
[ -e /vendor/etc/init/hw ] && chown 0:2000 /vendor/etc/init/hw
[ -e /vendor/etc/permissions ] && chown 0:2000 /vendor/etc/permissions
[ -e /vendor/etc/seccomp_policy ] && chown 0:2000 /vendor/etc/seccomp_policy
[ -e /vendor/etc/selinux ] && chown 0:2000 /vendor/etc/selinux
[ -e /vendor/etc/sensors ] && chown 0:2000 /vendor/etc/sensors
[ -e /vendor/etc/sensors/config ] && chown 0:2000 /vendor/etc/sensors/config
[ -e /vendor/etc/sensors/registry ] && chown 0:2000 /vendor/etc/sensors/registry
[ -e /vendor/etc/vintf ] && chown 0:2000 /vendor/etc/vintf
[ -e /vendor/etc/wifi ] && chown 0:2000 /vendor/etc/wifi
[ -e /vendor/firmware ] && chown 0:2000 /vendor/firmware
[ -e /vendor/firmware/wlan ] && chown 0:2000 /vendor/firmware/wlan
[ -e /vendor/firmware/wlan/qca_cld ] && chown 0:2000 /vendor/firmware/wlan/qca_cld
[ -e /vendor/firmware_mnt ] && chown 0:2000 /vendor/firmware_mnt
[ -e /vendor/lib ] && chown 0:2000 /vendor/lib
[ -e /vendor/lib/hw ] && chown 0:2000 /vendor/lib/hw
[ -e /vendor/lib/mediacas ] && chown 0:2000 /vendor/lib/mediacas
[ -e /vendor/lib/mediadrm ] && chown 0:2000 /vendor/lib/mediadrm
[ -e /vendor/lib/soundfx ] && chown 0:2000 /vendor/lib/soundfx
[ -e /vendor/lib64 ] && chown 0:2000 /vendor/lib64
[ -e /vendor/lib64/hw ] && chown 0:2000 /vendor/lib64/hw
[ -e /vendor/lib64/mediacas ] && chown 0:2000 /vendor/lib64/mediacas
[ -e /vendor/lib64/mediadrm ] && chown 0:2000 /vendor/lib64/mediadrm
[ -e /vendor/lib64/soundfx ] && chown 0:2000 /vendor/lib64/soundfx
[ -e /vendor/overlay ] && chown 0:2000 /vendor/overlay
[ -e /vendor/overlay/DisplayCutoutEmulationCorner ] && chown 0:2000 /vendor/overlay/DisplayCutoutEmulationCorner
[ -e /vendor/overlay/DisplayCutoutEmulationDouble ] && chown 0:2000 /vendor/overlay/DisplayCutoutEmulationDouble
[ -e /vendor/overlay/DisplayCutoutEmulationTall ] && chown 0:2000 /vendor/overlay/DisplayCutoutEmulationTall
[ -e /vendor/overlay/SysuiDarkTheme ] && chown 0:2000 /vendor/overlay/SysuiDarkTheme
[ -e /vendor/priv-app ] && chown 0:2000 /vendor/priv-app
[ -e /vendor/priv-app/ExtendedSettings ] && chown 0:2000 /vendor/priv-app/ExtendedSettings
[ -e /vendor/priv-app/QcRilAm ] && chown 0:2000 /vendor/priv-app/QcRilAm
[ -e /vendor/priv-app/TimeKeep ] && chown 0:2000 /vendor/priv-app/TimeKeep
[ -e /vendor/priv-app/TransPowerSensors ] && chown 0:2000 /vendor/priv-app/TransPowerSensors
[ -e /vendor/rfs ] && chown 0:2000 /vendor/rfs
[ -e /vendor/rfs/msm ] && chown 0:2000 /vendor/rfs/msm
[ -e /vendor/rfs/msm/adsp ] && chown 0:2000 /vendor/rfs/msm/adsp
[ -e /vendor/rfs/msm/adsp/readonly ] && chown 0:2000 /vendor/rfs/msm/adsp/readonly
[ -e /vendor/rfs/msm/adsp/readonly/vendor ] && chown 0:2000 /vendor/rfs/msm/adsp/readonly/vendor
[ -e /vendor/rfs/msm/cdsp ] && chown 0:2000 /vendor/rfs/msm/cdsp
[ -e /vendor/rfs/msm/cdsp/readonly ] && chown 0:2000 /vendor/rfs/msm/cdsp/readonly
[ -e /vendor/rfs/msm/cdsp/readonly/vendor ] && chown 0:2000 /vendor/rfs/msm/cdsp/readonly/vendor
[ -e /vendor/rfs/msm/mpss ] && chown 0:2000 /vendor/rfs/msm/mpss
[ -e /vendor/rfs/msm/mpss/readonly ] && chown 0:2000 /vendor/rfs/msm/mpss/readonly
[ -e /vendor/rfs/msm/mpss/readonly/vendor ] && chown 0:2000 /vendor/rfs/msm/mpss/readonly/vendor
[ -e /vendor/rfs/msm/slpi ] && chown 0:2000 /vendor/rfs/msm/slpi
[ -e /vendor/rfs/msm/slpi/readonly ] && chown 0:2000 /vendor/rfs/msm/slpi/readonly
[ -e /vendor/rfs/msm/slpi/readonly/vendor ] && chown 0:2000 /vendor/rfs/msm/slpi/readonly/vendor
[ -e /vendor/usr ] && chown 0:2000 /vendor/usr
[ -e /vendor/usr/idc ] && chown 0:2000 /vendor/usr/idc
[ -e /vendor/usr/keylayout ] && chown 0:2000 /vendor/usr/keylayout
